-- Inserting data into the 'faction' table

INSERT INTO faction (title, description, units) VALUES    ('Imperial Guard', 'The Imperial Guard, often referred to as the Astra Militarum, is the primary fighting force of the Imperium of Man. They are known for their massive armies of regular human soldiers and their unwavering loyalty to the Emperor.', 'Imperial Guardsman, Leman Russ Battle Tank, Chimera APC, Basilisk Artillery');
INSERT INTO faction (title, description, units) VALUES    ('Space Marines', 'The Space Marines are genetically enhanced superhuman soldiers, created to defend the Imperium. They are divided into various chapters, each with its own unique characteristics and combat doctrines.', 'Space Marine Tactical Squad, Assault Terminator Squad, Dreadnought, Rhino Transport');
INSERT INTO faction (title, description, units) VALUES    ('Eldar', 'The Eldar are an ancient and highly advanced race known for their psychic abilities and swift, agile warriors. They seek to preserve their dwindling civilization and protect the galaxy from chaos.', 'Eldar Guardians, Fire Prism Tank, Wraithlord, Howling Banshees');
INSERT INTO faction (title, description, units) VALUES    ('Chaos Space Marines', 'Corrupted Space Marines who have turned to Chaos, seeking power and favor from the Chaos Gods. They are formidable opponents and bring chaos and destruction wherever they go.', 'Chaos Space Marine Squad, Chaos Rhino, Daemon Prince, Havoc Squad');
INSERT INTO faction (title, description, units) VALUES    ('Tyranids', 'The Tyranids are a relentless hive mind of alien creatures, driven by an insatiable hunger to consume all biomass. They are a terrifying and invasive force in the galaxy.', 'Hormagaunts, Tyranid Warriors, Carnifex, Hive Tyrant');
INSERT INTO faction (title, description, units) VALUES    ('Orks', 'Orks are a warlike and brutal greenskin race that revels in violence and combat. They believe in the "bigger is better" philosophy and build massive warbands and machines.', 'Ork Boyz, Deff Dread, Warboss, Battlewagon');
INSERT INTO faction (title, description, units) VALUES    ('Tau Empire', 'The Tau Empire is a technologically advanced civilization with a strict caste system. They have advanced weaponry and seek to expand their influence through diplomacy and warfare.', 'Fire Warriors, Crisis Battlesuits, Hammerhead Gunship, Ethereal Caste');
INSERT INTO faction (title, description, units) VALUES    ('Necrons', 'The Necrons are an ancient race of robotic warriors who have awakened from eons of slumber. They seek to reclaim the galaxy for their own and have powerful, self-repairing bodies.', 'Necron Warriors, Annihilation Barge, Necron Overlord, Triarch Stalker');
INSERT INTO faction (title, description, units) VALUES    ('Adeptus Mechanicus', 'The Adeptus Mechanicus worships the Machine God and are the tech-priests of the Imperium. They are masters of technology and cybernetics, and they maintain the Imperium''s war machines.', 'Skitarii Rangers, Onager Dunecrawler, Tech-Priest Dominus, Kastelan Robots');
